using System;

namespace _5.Ulesanne
{
    class Program
    {
        static void Main(string[] args)
        {
            //making bike by generator
            var director = new Director();  // using director
            var autoGeneratedBike = new BikeBuilder();  //  using builder
            director.Bike = autoGeneratedBike;
            director.constructCustomBike();  // making a bike (custom, sport, touring, scooter) by using director

            Console.WriteLine("\n");

            var myBike = new BikeBuilder("BMW"); //making by builder own bike

            myBike.setBodyType("SPORT");
            myBike.setColour("WHITE-BlUE");
            myBike.setEngine(998, "MANUAL");
            myBike.setMillage(2017);
            myBike.GetPrice();
            myBike.addTurboCharge();
            myBike.addAutoClutch();
            myBike.PrintInfo();

            Console.WriteLine("\n");

            //making own bike (USING UI)
            Console.WriteLine("What MAKE of bike do you want? \n(Kawasaki, BMW, Yamaha, Suzuki....)");

            var ownBike = new BikeBuilder(Console.ReadLine());

            Console.WriteLine("\nChoose BODY TYPE \nSPORT, STREET, CHOOPER, CUSTOM, SCOOTER, TOURING or ENDURO?");
            ownBike.setBodyType(Console.ReadLine());

            Console.WriteLine("\nWhat COLOUR?");
            ownBike.setColour(Console.ReadLine());

            Console.WriteLine("\nHow many cc? (125, 400, 600, 1000...)?");
            int displacement = Convert.ToInt32(Console.ReadLine());

            Console.WriteLine("\nChoose year (2019, 2018, 2015...)");
            int year = Convert.ToInt32(Console.ReadLine());
            ownBike.setMillage(year);

            Console.WriteLine("\nChoose Transmission: AUTOMAT or MANUAL");
            string transmission = Console.ReadLine();

            ownBike.setEngine(displacement,  transmission);


            Console.WriteLine("\nAdd extra option: Auto-clutch (YES/NO)");
            if (Console.ReadLine() == "YES")
            {
                ownBike.addAutoClutch();
            }

            Console.WriteLine("\nAdd extra option: Anti-wheelie (YES/NO)");
            if (Console.ReadLine() == "YES")
            {
                ownBike.addAntiWheelie();
            }

            Console.WriteLine("\nAdd extra option: ABS (YES/NO)");
            if (Console.ReadLine() == "YES")
            {
                ownBike.addABS();
            }

            Console.WriteLine("\nAdd extra option: Turbo Charge (YES/NO)");
            if (Console.ReadLine() == "YES")
            {
                ownBike.addTurboCharge();
            }

            ownBike.GetPrice();
            Console.WriteLine("\n\n");
            ownBike.PrintInfo();
        }
    }
}
